project_id = "xnvqmukgsjluwpoosohf"

[functions.submit-attempt]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.seed-courses]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false
