project_id = "xnvqmukgsjluwpoosohf"

[functions.submit-attempt]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.seed-courses]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.dialogue]
verify_jwt = false

[functions.seed-descriptor-lessons]
verify_jwt = false

[functions.seed-descriptors]
verify_jwt = false

[functions.sync-curriculum]
verify_jwt = false
